/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as appRouteRouteImport } from './routes/(app)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as authSignupRouteImport } from './routes/(auth)/signup'
import { Route as authSigninRouteImport } from './routes/(auth)/signin'
import { Route as ApiNotificationSseRouteImport } from './routes/api/notification/sse'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as appDashboardOrganizationsRouteImport } from './routes/(app)/dashboard/organizations'
import { Route as appDashboardadminRouteRouteImport } from './routes/(app)/dashboard/(admin)/route'
import { Route as appDashboardadminIndexRouteImport } from './routes/(app)/dashboard/(admin)/index'
import { Route as ApiNotificationCustomerSseRouteImport } from './routes/api/notification/customer.sse'
import { Route as publicSupportProjectIdChatWidgetRouteImport } from './routes/(public)/support.$projectId/chat-widget'
import { Route as appDashboardadminUsersRouteImport } from './routes/(app)/dashboard/(admin)/users'
import { Route as appDashboardProjectProjectIdRouteRouteImport } from './routes/(app)/dashboard/project.$projectId/route'
import { Route as appDashboardOrgOrganizationIdRouteRouteImport } from './routes/(app)/dashboard/org.$organizationId/route'
import { Route as appDashboardProjectProjectIdIndexRouteImport } from './routes/(app)/dashboard/project.$projectId/index'
import { Route as appDashboardOrgOrganizationIdIndexRouteImport } from './routes/(app)/dashboard/org.$organizationId/index'
import { Route as appDashboardProjectProjectIdTicketsRouteImport } from './routes/(app)/dashboard/project.$projectId/tickets'
import { Route as appDashboardProjectProjectIdSettingsRouteImport } from './routes/(app)/dashboard/project.$projectId/settings'
import { Route as appDashboardProjectProjectIdChatSupportRouteImport } from './routes/(app)/dashboard/project.$projectId/chat-support'
import { Route as appDashboardProjectProjectIdAgentsRouteImport } from './routes/(app)/dashboard/project.$projectId/agents'
import { Route as appDashboardOrgOrganizationIdUsageRouteImport } from './routes/(app)/dashboard/org.$organizationId/usage'
import { Route as appDashboardOrgOrganizationIdTeamsRouteImport } from './routes/(app)/dashboard/org.$organizationId/teams'
import { Route as appDashboardOrgOrganizationIdSettingsRouteImport } from './routes/(app)/dashboard/org.$organizationId/settings'
import { Route as appDashboardOrgOrganizationIdIntegrationsRouteImport } from './routes/(app)/dashboard/org.$organizationId/integrations'
import { Route as appDashboardOrgOrganizationIdBillingRouteImport } from './routes/(app)/dashboard/org.$organizationId/billing'

const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignupRoute = authSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => authRouteRoute,
} as any)
const authSigninRoute = authSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => authRouteRoute,
} as any)
const ApiNotificationSseRoute = ApiNotificationSseRouteImport.update({
  id: '/api/notification/sse',
  path: '/api/notification/sse',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const appDashboardOrganizationsRoute =
  appDashboardOrganizationsRouteImport.update({
    id: '/dashboard/organizations',
    path: '/dashboard/organizations',
    getParentRoute: () => appRouteRoute,
  } as any)
const appDashboardadminRouteRoute = appDashboardadminRouteRouteImport.update({
  id: '/dashboard/(admin)',
  path: '/dashboard',
  getParentRoute: () => appRouteRoute,
} as any)
const appDashboardadminIndexRoute = appDashboardadminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appDashboardadminRouteRoute,
} as any)
const ApiNotificationCustomerSseRoute =
  ApiNotificationCustomerSseRouteImport.update({
    id: '/api/notification/customer/sse',
    path: '/api/notification/customer/sse',
    getParentRoute: () => rootRouteImport,
  } as any)
const publicSupportProjectIdChatWidgetRoute =
  publicSupportProjectIdChatWidgetRouteImport.update({
    id: '/(public)/support/$projectId/chat-widget',
    path: '/support/$projectId/chat-widget',
    getParentRoute: () => rootRouteImport,
  } as any)
const appDashboardadminUsersRoute = appDashboardadminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => appDashboardadminRouteRoute,
} as any)
const appDashboardProjectProjectIdRouteRoute =
  appDashboardProjectProjectIdRouteRouteImport.update({
    id: '/dashboard/project/$projectId',
    path: '/dashboard/project/$projectId',
    getParentRoute: () => appRouteRoute,
  } as any)
const appDashboardOrgOrganizationIdRouteRoute =
  appDashboardOrgOrganizationIdRouteRouteImport.update({
    id: '/dashboard/org/$organizationId',
    path: '/dashboard/org/$organizationId',
    getParentRoute: () => appRouteRoute,
  } as any)
const appDashboardProjectProjectIdIndexRoute =
  appDashboardProjectProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => appDashboardProjectProjectIdRouteRoute,
  } as any)
const appDashboardOrgOrganizationIdIndexRoute =
  appDashboardOrgOrganizationIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => appDashboardOrgOrganizationIdRouteRoute,
  } as any)
const appDashboardProjectProjectIdTicketsRoute =
  appDashboardProjectProjectIdTicketsRouteImport.update({
    id: '/tickets',
    path: '/tickets',
    getParentRoute: () => appDashboardProjectProjectIdRouteRoute,
  } as any)
const appDashboardProjectProjectIdSettingsRoute =
  appDashboardProjectProjectIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => appDashboardProjectProjectIdRouteRoute,
  } as any)
const appDashboardProjectProjectIdChatSupportRoute =
  appDashboardProjectProjectIdChatSupportRouteImport.update({
    id: '/chat-support',
    path: '/chat-support',
    getParentRoute: () => appDashboardProjectProjectIdRouteRoute,
  } as any)
const appDashboardProjectProjectIdAgentsRoute =
  appDashboardProjectProjectIdAgentsRouteImport.update({
    id: '/agents',
    path: '/agents',
    getParentRoute: () => appDashboardProjectProjectIdRouteRoute,
  } as any)
const appDashboardOrgOrganizationIdUsageRoute =
  appDashboardOrgOrganizationIdUsageRouteImport.update({
    id: '/usage',
    path: '/usage',
    getParentRoute: () => appDashboardOrgOrganizationIdRouteRoute,
  } as any)
const appDashboardOrgOrganizationIdTeamsRoute =
  appDashboardOrgOrganizationIdTeamsRouteImport.update({
    id: '/teams',
    path: '/teams',
    getParentRoute: () => appDashboardOrgOrganizationIdRouteRoute,
  } as any)
const appDashboardOrgOrganizationIdSettingsRoute =
  appDashboardOrgOrganizationIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => appDashboardOrgOrganizationIdRouteRoute,
  } as any)
const appDashboardOrgOrganizationIdIntegrationsRoute =
  appDashboardOrgOrganizationIdIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => appDashboardOrgOrganizationIdRouteRoute,
  } as any)
const appDashboardOrgOrganizationIdBillingRoute =
  appDashboardOrgOrganizationIdBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => appDashboardOrgOrganizationIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/signin': typeof authSigninRoute
  '/signup': typeof authSignupRoute
  '/dashboard': typeof appDashboardadminRouteRouteWithChildren
  '/dashboard/organizations': typeof appDashboardOrganizationsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/notification/sse': typeof ApiNotificationSseRoute
  '/dashboard/org/$organizationId': typeof appDashboardOrgOrganizationIdRouteRouteWithChildren
  '/dashboard/project/$projectId': typeof appDashboardProjectProjectIdRouteRouteWithChildren
  '/dashboard/users': typeof appDashboardadminUsersRoute
  '/support/$projectId/chat-widget': typeof publicSupportProjectIdChatWidgetRoute
  '/api/notification/customer/sse': typeof ApiNotificationCustomerSseRoute
  '/dashboard/': typeof appDashboardadminIndexRoute
  '/dashboard/org/$organizationId/billing': typeof appDashboardOrgOrganizationIdBillingRoute
  '/dashboard/org/$organizationId/integrations': typeof appDashboardOrgOrganizationIdIntegrationsRoute
  '/dashboard/org/$organizationId/settings': typeof appDashboardOrgOrganizationIdSettingsRoute
  '/dashboard/org/$organizationId/teams': typeof appDashboardOrgOrganizationIdTeamsRoute
  '/dashboard/org/$organizationId/usage': typeof appDashboardOrgOrganizationIdUsageRoute
  '/dashboard/project/$projectId/agents': typeof appDashboardProjectProjectIdAgentsRoute
  '/dashboard/project/$projectId/chat-support': typeof appDashboardProjectProjectIdChatSupportRoute
  '/dashboard/project/$projectId/settings': typeof appDashboardProjectProjectIdSettingsRoute
  '/dashboard/project/$projectId/tickets': typeof appDashboardProjectProjectIdTicketsRoute
  '/dashboard/org/$organizationId/': typeof appDashboardOrgOrganizationIdIndexRoute
  '/dashboard/project/$projectId/': typeof appDashboardProjectProjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signin': typeof authSigninRoute
  '/signup': typeof authSignupRoute
  '/dashboard/organizations': typeof appDashboardOrganizationsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/notification/sse': typeof ApiNotificationSseRoute
  '/dashboard/users': typeof appDashboardadminUsersRoute
  '/support/$projectId/chat-widget': typeof publicSupportProjectIdChatWidgetRoute
  '/api/notification/customer/sse': typeof ApiNotificationCustomerSseRoute
  '/dashboard': typeof appDashboardadminIndexRoute
  '/dashboard/org/$organizationId/billing': typeof appDashboardOrgOrganizationIdBillingRoute
  '/dashboard/org/$organizationId/integrations': typeof appDashboardOrgOrganizationIdIntegrationsRoute
  '/dashboard/org/$organizationId/settings': typeof appDashboardOrgOrganizationIdSettingsRoute
  '/dashboard/org/$organizationId/teams': typeof appDashboardOrgOrganizationIdTeamsRoute
  '/dashboard/org/$organizationId/usage': typeof appDashboardOrgOrganizationIdUsageRoute
  '/dashboard/project/$projectId/agents': typeof appDashboardProjectProjectIdAgentsRoute
  '/dashboard/project/$projectId/chat-support': typeof appDashboardProjectProjectIdChatSupportRoute
  '/dashboard/project/$projectId/settings': typeof appDashboardProjectProjectIdSettingsRoute
  '/dashboard/project/$projectId/tickets': typeof appDashboardProjectProjectIdTicketsRoute
  '/dashboard/org/$organizationId': typeof appDashboardOrgOrganizationIdIndexRoute
  '/dashboard/project/$projectId': typeof appDashboardProjectProjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(app)': typeof appRouteRouteWithChildren
  '/(auth)': typeof authRouteRouteWithChildren
  '/(auth)/signin': typeof authSigninRoute
  '/(auth)/signup': typeof authSignupRoute
  '/(app)/dashboard/(admin)': typeof appDashboardadminRouteRouteWithChildren
  '/(app)/dashboard/organizations': typeof appDashboardOrganizationsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/notification/sse': typeof ApiNotificationSseRoute
  '/(app)/dashboard/org/$organizationId': typeof appDashboardOrgOrganizationIdRouteRouteWithChildren
  '/(app)/dashboard/project/$projectId': typeof appDashboardProjectProjectIdRouteRouteWithChildren
  '/(app)/dashboard/(admin)/users': typeof appDashboardadminUsersRoute
  '/(public)/support/$projectId/chat-widget': typeof publicSupportProjectIdChatWidgetRoute
  '/api/notification/customer/sse': typeof ApiNotificationCustomerSseRoute
  '/(app)/dashboard/(admin)/': typeof appDashboardadminIndexRoute
  '/(app)/dashboard/org/$organizationId/billing': typeof appDashboardOrgOrganizationIdBillingRoute
  '/(app)/dashboard/org/$organizationId/integrations': typeof appDashboardOrgOrganizationIdIntegrationsRoute
  '/(app)/dashboard/org/$organizationId/settings': typeof appDashboardOrgOrganizationIdSettingsRoute
  '/(app)/dashboard/org/$organizationId/teams': typeof appDashboardOrgOrganizationIdTeamsRoute
  '/(app)/dashboard/org/$organizationId/usage': typeof appDashboardOrgOrganizationIdUsageRoute
  '/(app)/dashboard/project/$projectId/agents': typeof appDashboardProjectProjectIdAgentsRoute
  '/(app)/dashboard/project/$projectId/chat-support': typeof appDashboardProjectProjectIdChatSupportRoute
  '/(app)/dashboard/project/$projectId/settings': typeof appDashboardProjectProjectIdSettingsRoute
  '/(app)/dashboard/project/$projectId/tickets': typeof appDashboardProjectProjectIdTicketsRoute
  '/(app)/dashboard/org/$organizationId/': typeof appDashboardOrgOrganizationIdIndexRoute
  '/(app)/dashboard/project/$projectId/': typeof appDashboardProjectProjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/signin'
    | '/signup'
    | '/dashboard'
    | '/dashboard/organizations'
    | '/api/auth/$'
    | '/api/notification/sse'
    | '/dashboard/org/$organizationId'
    | '/dashboard/project/$projectId'
    | '/dashboard/users'
    | '/support/$projectId/chat-widget'
    | '/api/notification/customer/sse'
    | '/dashboard/'
    | '/dashboard/org/$organizationId/billing'
    | '/dashboard/org/$organizationId/integrations'
    | '/dashboard/org/$organizationId/settings'
    | '/dashboard/org/$organizationId/teams'
    | '/dashboard/org/$organizationId/usage'
    | '/dashboard/project/$projectId/agents'
    | '/dashboard/project/$projectId/chat-support'
    | '/dashboard/project/$projectId/settings'
    | '/dashboard/project/$projectId/tickets'
    | '/dashboard/org/$organizationId/'
    | '/dashboard/project/$projectId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signin'
    | '/signup'
    | '/dashboard/organizations'
    | '/api/auth/$'
    | '/api/notification/sse'
    | '/dashboard/users'
    | '/support/$projectId/chat-widget'
    | '/api/notification/customer/sse'
    | '/dashboard'
    | '/dashboard/org/$organizationId/billing'
    | '/dashboard/org/$organizationId/integrations'
    | '/dashboard/org/$organizationId/settings'
    | '/dashboard/org/$organizationId/teams'
    | '/dashboard/org/$organizationId/usage'
    | '/dashboard/project/$projectId/agents'
    | '/dashboard/project/$projectId/chat-support'
    | '/dashboard/project/$projectId/settings'
    | '/dashboard/project/$projectId/tickets'
    | '/dashboard/org/$organizationId'
    | '/dashboard/project/$projectId'
  id:
    | '__root__'
    | '/'
    | '/(app)'
    | '/(auth)'
    | '/(auth)/signin'
    | '/(auth)/signup'
    | '/(app)/dashboard/(admin)'
    | '/(app)/dashboard/organizations'
    | '/api/auth/$'
    | '/api/notification/sse'
    | '/(app)/dashboard/org/$organizationId'
    | '/(app)/dashboard/project/$projectId'
    | '/(app)/dashboard/(admin)/users'
    | '/(public)/support/$projectId/chat-widget'
    | '/api/notification/customer/sse'
    | '/(app)/dashboard/(admin)/'
    | '/(app)/dashboard/org/$organizationId/billing'
    | '/(app)/dashboard/org/$organizationId/integrations'
    | '/(app)/dashboard/org/$organizationId/settings'
    | '/(app)/dashboard/org/$organizationId/teams'
    | '/(app)/dashboard/org/$organizationId/usage'
    | '/(app)/dashboard/project/$projectId/agents'
    | '/(app)/dashboard/project/$projectId/chat-support'
    | '/(app)/dashboard/project/$projectId/settings'
    | '/(app)/dashboard/project/$projectId/tickets'
    | '/(app)/dashboard/org/$organizationId/'
    | '/(app)/dashboard/project/$projectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  appRouteRoute: typeof appRouteRouteWithChildren
  authRouteRoute: typeof authRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiNotificationSseRoute: typeof ApiNotificationSseRoute
  publicSupportProjectIdChatWidgetRoute: typeof publicSupportProjectIdChatWidgetRoute
  ApiNotificationCustomerSseRoute: typeof ApiNotificationCustomerSseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)': {
      id: '/(app)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/signup': {
      id: '/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/signin': {
      id: '/(auth)/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof authSigninRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/api/notification/sse': {
      id: '/api/notification/sse'
      path: '/api/notification/sse'
      fullPath: '/api/notification/sse'
      preLoaderRoute: typeof ApiNotificationSseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/dashboard/organizations': {
      id: '/(app)/dashboard/organizations'
      path: '/dashboard/organizations'
      fullPath: '/dashboard/organizations'
      preLoaderRoute: typeof appDashboardOrganizationsRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/dashboard/(admin)': {
      id: '/(app)/dashboard/(admin)'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof appDashboardadminRouteRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/dashboard/(admin)/': {
      id: '/(app)/dashboard/(admin)/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof appDashboardadminIndexRouteImport
      parentRoute: typeof appDashboardadminRouteRoute
    }
    '/api/notification/customer/sse': {
      id: '/api/notification/customer/sse'
      path: '/api/notification/customer/sse'
      fullPath: '/api/notification/customer/sse'
      preLoaderRoute: typeof ApiNotificationCustomerSseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/support/$projectId/chat-widget': {
      id: '/(public)/support/$projectId/chat-widget'
      path: '/support/$projectId/chat-widget'
      fullPath: '/support/$projectId/chat-widget'
      preLoaderRoute: typeof publicSupportProjectIdChatWidgetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/dashboard/(admin)/users': {
      id: '/(app)/dashboard/(admin)/users'
      path: '/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof appDashboardadminUsersRouteImport
      parentRoute: typeof appDashboardadminRouteRoute
    }
    '/(app)/dashboard/project/$projectId': {
      id: '/(app)/dashboard/project/$projectId'
      path: '/dashboard/project/$projectId'
      fullPath: '/dashboard/project/$projectId'
      preLoaderRoute: typeof appDashboardProjectProjectIdRouteRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/dashboard/org/$organizationId': {
      id: '/(app)/dashboard/org/$organizationId'
      path: '/dashboard/org/$organizationId'
      fullPath: '/dashboard/org/$organizationId'
      preLoaderRoute: typeof appDashboardOrgOrganizationIdRouteRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/dashboard/project/$projectId/': {
      id: '/(app)/dashboard/project/$projectId/'
      path: '/'
      fullPath: '/dashboard/project/$projectId/'
      preLoaderRoute: typeof appDashboardProjectProjectIdIndexRouteImport
      parentRoute: typeof appDashboardProjectProjectIdRouteRoute
    }
    '/(app)/dashboard/org/$organizationId/': {
      id: '/(app)/dashboard/org/$organizationId/'
      path: '/'
      fullPath: '/dashboard/org/$organizationId/'
      preLoaderRoute: typeof appDashboardOrgOrganizationIdIndexRouteImport
      parentRoute: typeof appDashboardOrgOrganizationIdRouteRoute
    }
    '/(app)/dashboard/project/$projectId/tickets': {
      id: '/(app)/dashboard/project/$projectId/tickets'
      path: '/tickets'
      fullPath: '/dashboard/project/$projectId/tickets'
      preLoaderRoute: typeof appDashboardProjectProjectIdTicketsRouteImport
      parentRoute: typeof appDashboardProjectProjectIdRouteRoute
    }
    '/(app)/dashboard/project/$projectId/settings': {
      id: '/(app)/dashboard/project/$projectId/settings'
      path: '/settings'
      fullPath: '/dashboard/project/$projectId/settings'
      preLoaderRoute: typeof appDashboardProjectProjectIdSettingsRouteImport
      parentRoute: typeof appDashboardProjectProjectIdRouteRoute
    }
    '/(app)/dashboard/project/$projectId/chat-support': {
      id: '/(app)/dashboard/project/$projectId/chat-support'
      path: '/chat-support'
      fullPath: '/dashboard/project/$projectId/chat-support'
      preLoaderRoute: typeof appDashboardProjectProjectIdChatSupportRouteImport
      parentRoute: typeof appDashboardProjectProjectIdRouteRoute
    }
    '/(app)/dashboard/project/$projectId/agents': {
      id: '/(app)/dashboard/project/$projectId/agents'
      path: '/agents'
      fullPath: '/dashboard/project/$projectId/agents'
      preLoaderRoute: typeof appDashboardProjectProjectIdAgentsRouteImport
      parentRoute: typeof appDashboardProjectProjectIdRouteRoute
    }
    '/(app)/dashboard/org/$organizationId/usage': {
      id: '/(app)/dashboard/org/$organizationId/usage'
      path: '/usage'
      fullPath: '/dashboard/org/$organizationId/usage'
      preLoaderRoute: typeof appDashboardOrgOrganizationIdUsageRouteImport
      parentRoute: typeof appDashboardOrgOrganizationIdRouteRoute
    }
    '/(app)/dashboard/org/$organizationId/teams': {
      id: '/(app)/dashboard/org/$organizationId/teams'
      path: '/teams'
      fullPath: '/dashboard/org/$organizationId/teams'
      preLoaderRoute: typeof appDashboardOrgOrganizationIdTeamsRouteImport
      parentRoute: typeof appDashboardOrgOrganizationIdRouteRoute
    }
    '/(app)/dashboard/org/$organizationId/settings': {
      id: '/(app)/dashboard/org/$organizationId/settings'
      path: '/settings'
      fullPath: '/dashboard/org/$organizationId/settings'
      preLoaderRoute: typeof appDashboardOrgOrganizationIdSettingsRouteImport
      parentRoute: typeof appDashboardOrgOrganizationIdRouteRoute
    }
    '/(app)/dashboard/org/$organizationId/integrations': {
      id: '/(app)/dashboard/org/$organizationId/integrations'
      path: '/integrations'
      fullPath: '/dashboard/org/$organizationId/integrations'
      preLoaderRoute: typeof appDashboardOrgOrganizationIdIntegrationsRouteImport
      parentRoute: typeof appDashboardOrgOrganizationIdRouteRoute
    }
    '/(app)/dashboard/org/$organizationId/billing': {
      id: '/(app)/dashboard/org/$organizationId/billing'
      path: '/billing'
      fullPath: '/dashboard/org/$organizationId/billing'
      preLoaderRoute: typeof appDashboardOrgOrganizationIdBillingRouteImport
      parentRoute: typeof appDashboardOrgOrganizationIdRouteRoute
    }
  }
}

interface appDashboardadminRouteRouteChildren {
  appDashboardadminUsersRoute: typeof appDashboardadminUsersRoute
  appDashboardadminIndexRoute: typeof appDashboardadminIndexRoute
}

const appDashboardadminRouteRouteChildren: appDashboardadminRouteRouteChildren =
  {
    appDashboardadminUsersRoute: appDashboardadminUsersRoute,
    appDashboardadminIndexRoute: appDashboardadminIndexRoute,
  }

const appDashboardadminRouteRouteWithChildren =
  appDashboardadminRouteRoute._addFileChildren(
    appDashboardadminRouteRouteChildren,
  )

interface appDashboardOrgOrganizationIdRouteRouteChildren {
  appDashboardOrgOrganizationIdBillingRoute: typeof appDashboardOrgOrganizationIdBillingRoute
  appDashboardOrgOrganizationIdIntegrationsRoute: typeof appDashboardOrgOrganizationIdIntegrationsRoute
  appDashboardOrgOrganizationIdSettingsRoute: typeof appDashboardOrgOrganizationIdSettingsRoute
  appDashboardOrgOrganizationIdTeamsRoute: typeof appDashboardOrgOrganizationIdTeamsRoute
  appDashboardOrgOrganizationIdUsageRoute: typeof appDashboardOrgOrganizationIdUsageRoute
  appDashboardOrgOrganizationIdIndexRoute: typeof appDashboardOrgOrganizationIdIndexRoute
}

const appDashboardOrgOrganizationIdRouteRouteChildren: appDashboardOrgOrganizationIdRouteRouteChildren =
  {
    appDashboardOrgOrganizationIdBillingRoute:
      appDashboardOrgOrganizationIdBillingRoute,
    appDashboardOrgOrganizationIdIntegrationsRoute:
      appDashboardOrgOrganizationIdIntegrationsRoute,
    appDashboardOrgOrganizationIdSettingsRoute:
      appDashboardOrgOrganizationIdSettingsRoute,
    appDashboardOrgOrganizationIdTeamsRoute:
      appDashboardOrgOrganizationIdTeamsRoute,
    appDashboardOrgOrganizationIdUsageRoute:
      appDashboardOrgOrganizationIdUsageRoute,
    appDashboardOrgOrganizationIdIndexRoute:
      appDashboardOrgOrganizationIdIndexRoute,
  }

const appDashboardOrgOrganizationIdRouteRouteWithChildren =
  appDashboardOrgOrganizationIdRouteRoute._addFileChildren(
    appDashboardOrgOrganizationIdRouteRouteChildren,
  )

interface appDashboardProjectProjectIdRouteRouteChildren {
  appDashboardProjectProjectIdAgentsRoute: typeof appDashboardProjectProjectIdAgentsRoute
  appDashboardProjectProjectIdChatSupportRoute: typeof appDashboardProjectProjectIdChatSupportRoute
  appDashboardProjectProjectIdSettingsRoute: typeof appDashboardProjectProjectIdSettingsRoute
  appDashboardProjectProjectIdTicketsRoute: typeof appDashboardProjectProjectIdTicketsRoute
  appDashboardProjectProjectIdIndexRoute: typeof appDashboardProjectProjectIdIndexRoute
}

const appDashboardProjectProjectIdRouteRouteChildren: appDashboardProjectProjectIdRouteRouteChildren =
  {
    appDashboardProjectProjectIdAgentsRoute:
      appDashboardProjectProjectIdAgentsRoute,
    appDashboardProjectProjectIdChatSupportRoute:
      appDashboardProjectProjectIdChatSupportRoute,
    appDashboardProjectProjectIdSettingsRoute:
      appDashboardProjectProjectIdSettingsRoute,
    appDashboardProjectProjectIdTicketsRoute:
      appDashboardProjectProjectIdTicketsRoute,
    appDashboardProjectProjectIdIndexRoute:
      appDashboardProjectProjectIdIndexRoute,
  }

const appDashboardProjectProjectIdRouteRouteWithChildren =
  appDashboardProjectProjectIdRouteRoute._addFileChildren(
    appDashboardProjectProjectIdRouteRouteChildren,
  )

interface appRouteRouteChildren {
  appDashboardadminRouteRoute: typeof appDashboardadminRouteRouteWithChildren
  appDashboardOrganizationsRoute: typeof appDashboardOrganizationsRoute
  appDashboardOrgOrganizationIdRouteRoute: typeof appDashboardOrgOrganizationIdRouteRouteWithChildren
  appDashboardProjectProjectIdRouteRoute: typeof appDashboardProjectProjectIdRouteRouteWithChildren
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appDashboardadminRouteRoute: appDashboardadminRouteRouteWithChildren,
  appDashboardOrganizationsRoute: appDashboardOrganizationsRoute,
  appDashboardOrgOrganizationIdRouteRoute:
    appDashboardOrgOrganizationIdRouteRouteWithChildren,
  appDashboardProjectProjectIdRouteRoute:
    appDashboardProjectProjectIdRouteRouteWithChildren,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

interface authRouteRouteChildren {
  authSigninRoute: typeof authSigninRoute
  authSignupRoute: typeof authSignupRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authSigninRoute: authSigninRoute,
  authSignupRoute: authSignupRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  appRouteRoute: appRouteRouteWithChildren,
  authRouteRoute: authRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiNotificationSseRoute: ApiNotificationSseRoute,
  publicSupportProjectIdChatWidgetRoute: publicSupportProjectIdChatWidgetRoute,
  ApiNotificationCustomerSseRoute: ApiNotificationCustomerSseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
