/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as appRouteRouteImport } from './routes/(app)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTranslateRouteImport } from './routes/api/translate'
import { Route as publicChatRouteImport } from './routes/(public)/chat'
import { Route as authSignupRouteImport } from './routes/(auth)/signup'
import { Route as authSigninRouteImport } from './routes/(auth)/signin'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as ApiAttachmentsIndexRouteImport } from './routes/api/attachments/index'
import { Route as ApiNotificationSseRouteImport } from './routes/api/notification/sse'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAttachmentsIdRouteImport } from './routes/api/attachments/$id'
import { Route as appDashboardTriageRouteImport } from './routes/(app)/dashboard/triage'
import { Route as appDashboardOrganizationsRouteImport } from './routes/(app)/dashboard/organizations'
import { Route as publicSupportProjectSlugManifestRouteImport } from './routes/(public)/support.$projectSlug/manifest'
import { Route as publicSupportProjectSlugChatWidgetRouteImport } from './routes/(public)/support.$projectSlug/chat-widget'
import { Route as appDashboardProjectProjectSlugRouteRouteImport } from './routes/(app)/dashboard/project.$projectSlug/route'
import { Route as appDashboardOrgOrganizationSlugRouteRouteImport } from './routes/(app)/dashboard/org.$organizationSlug/route'
import { Route as appDashboardProjectProjectSlugIndexRouteImport } from './routes/(app)/dashboard/project.$projectSlug/index'
import { Route as appDashboardOrgOrganizationSlugIndexRouteImport } from './routes/(app)/dashboard/org.$organizationSlug/index'
import { Route as appDashboardProjectProjectSlugTicketsRouteImport } from './routes/(app)/dashboard/project.$projectSlug/tickets'
import { Route as appDashboardProjectProjectSlugSettingsRouteImport } from './routes/(app)/dashboard/project.$projectSlug/settings'
import { Route as appDashboardProjectProjectSlugCustomersRouteImport } from './routes/(app)/dashboard/project.$projectSlug/customers'
import { Route as appDashboardProjectProjectSlugChatSupportRouteImport } from './routes/(app)/dashboard/project.$projectSlug/chat-support'
import { Route as appDashboardProjectProjectSlugAgentsRouteImport } from './routes/(app)/dashboard/project.$projectSlug/agents'
import { Route as appDashboardOrgOrganizationSlugUsageRouteImport } from './routes/(app)/dashboard/org.$organizationSlug/usage'
import { Route as appDashboardOrgOrganizationSlugTeamsRouteImport } from './routes/(app)/dashboard/org.$organizationSlug/teams'
import { Route as appDashboardOrgOrganizationSlugSettingsRouteImport } from './routes/(app)/dashboard/org.$organizationSlug/settings'
import { Route as appDashboardOrgOrganizationSlugIntegrationsRouteImport } from './routes/(app)/dashboard/org.$organizationSlug/integrations'
import { Route as appDashboardOrgOrganizationSlugBillingRouteImport } from './routes/(app)/dashboard/org.$organizationSlug/billing'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranslateRoute = ApiTranslateRouteImport.update({
  id: '/api/translate',
  path: '/api/translate',
  getParentRoute: () => rootRouteImport,
} as any)
const publicChatRoute = publicChatRouteImport.update({
  id: '/(public)/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignupRoute = authSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => authRouteRoute,
} as any)
const authSigninRoute = authSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => authRouteRoute,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => authRouteRoute,
} as any)
const ApiAttachmentsIndexRoute = ApiAttachmentsIndexRouteImport.update({
  id: '/api/attachments/',
  path: '/api/attachments/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotificationSseRoute = ApiNotificationSseRouteImport.update({
  id: '/api/notification/sse',
  path: '/api/notification/sse',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAttachmentsIdRoute = ApiAttachmentsIdRouteImport.update({
  id: '/api/attachments/$id',
  path: '/api/attachments/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const appDashboardTriageRoute = appDashboardTriageRouteImport.update({
  id: '/dashboard/triage',
  path: '/dashboard/triage',
  getParentRoute: () => appRouteRoute,
} as any)
const appDashboardOrganizationsRoute =
  appDashboardOrganizationsRouteImport.update({
    id: '/dashboard/organizations',
    path: '/dashboard/organizations',
    getParentRoute: () => appRouteRoute,
  } as any)
const publicSupportProjectSlugManifestRoute =
  publicSupportProjectSlugManifestRouteImport.update({
    id: '/(public)/support/$projectSlug/manifest',
    path: '/support/$projectSlug/manifest',
    getParentRoute: () => rootRouteImport,
  } as any)
const publicSupportProjectSlugChatWidgetRoute =
  publicSupportProjectSlugChatWidgetRouteImport.update({
    id: '/(public)/support/$projectSlug/chat-widget',
    path: '/support/$projectSlug/chat-widget',
    getParentRoute: () => rootRouteImport,
  } as any)
const appDashboardProjectProjectSlugRouteRoute =
  appDashboardProjectProjectSlugRouteRouteImport.update({
    id: '/dashboard/project/$projectSlug',
    path: '/dashboard/project/$projectSlug',
    getParentRoute: () => appRouteRoute,
  } as any)
const appDashboardOrgOrganizationSlugRouteRoute =
  appDashboardOrgOrganizationSlugRouteRouteImport.update({
    id: '/dashboard/org/$organizationSlug',
    path: '/dashboard/org/$organizationSlug',
    getParentRoute: () => appRouteRoute,
  } as any)
const appDashboardProjectProjectSlugIndexRoute =
  appDashboardProjectProjectSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => appDashboardProjectProjectSlugRouteRoute,
  } as any)
const appDashboardOrgOrganizationSlugIndexRoute =
  appDashboardOrgOrganizationSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => appDashboardOrgOrganizationSlugRouteRoute,
  } as any)
const appDashboardProjectProjectSlugTicketsRoute =
  appDashboardProjectProjectSlugTicketsRouteImport.update({
    id: '/tickets',
    path: '/tickets',
    getParentRoute: () => appDashboardProjectProjectSlugRouteRoute,
  } as any)
const appDashboardProjectProjectSlugSettingsRoute =
  appDashboardProjectProjectSlugSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => appDashboardProjectProjectSlugRouteRoute,
  } as any)
const appDashboardProjectProjectSlugCustomersRoute =
  appDashboardProjectProjectSlugCustomersRouteImport.update({
    id: '/customers',
    path: '/customers',
    getParentRoute: () => appDashboardProjectProjectSlugRouteRoute,
  } as any)
const appDashboardProjectProjectSlugChatSupportRoute =
  appDashboardProjectProjectSlugChatSupportRouteImport.update({
    id: '/chat-support',
    path: '/chat-support',
    getParentRoute: () => appDashboardProjectProjectSlugRouteRoute,
  } as any)
const appDashboardProjectProjectSlugAgentsRoute =
  appDashboardProjectProjectSlugAgentsRouteImport.update({
    id: '/agents',
    path: '/agents',
    getParentRoute: () => appDashboardProjectProjectSlugRouteRoute,
  } as any)
const appDashboardOrgOrganizationSlugUsageRoute =
  appDashboardOrgOrganizationSlugUsageRouteImport.update({
    id: '/usage',
    path: '/usage',
    getParentRoute: () => appDashboardOrgOrganizationSlugRouteRoute,
  } as any)
const appDashboardOrgOrganizationSlugTeamsRoute =
  appDashboardOrgOrganizationSlugTeamsRouteImport.update({
    id: '/teams',
    path: '/teams',
    getParentRoute: () => appDashboardOrgOrganizationSlugRouteRoute,
  } as any)
const appDashboardOrgOrganizationSlugSettingsRoute =
  appDashboardOrgOrganizationSlugSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => appDashboardOrgOrganizationSlugRouteRoute,
  } as any)
const appDashboardOrgOrganizationSlugIntegrationsRoute =
  appDashboardOrgOrganizationSlugIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => appDashboardOrgOrganizationSlugRouteRoute,
  } as any)
const appDashboardOrgOrganizationSlugBillingRoute =
  appDashboardOrgOrganizationSlugBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => appDashboardOrgOrganizationSlugRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/reset-password': typeof ResetPasswordRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/signin': typeof authSigninRoute
  '/signup': typeof authSignupRoute
  '/chat': typeof publicChatRoute
  '/api/translate': typeof ApiTranslateRoute
  '/dashboard/organizations': typeof appDashboardOrganizationsRoute
  '/dashboard/triage': typeof appDashboardTriageRoute
  '/api/attachments/$id': typeof ApiAttachmentsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/notification/sse': typeof ApiNotificationSseRoute
  '/api/attachments/': typeof ApiAttachmentsIndexRoute
  '/dashboard/org/$organizationSlug': typeof appDashboardOrgOrganizationSlugRouteRouteWithChildren
  '/dashboard/project/$projectSlug': typeof appDashboardProjectProjectSlugRouteRouteWithChildren
  '/support/$projectSlug/chat-widget': typeof publicSupportProjectSlugChatWidgetRoute
  '/support/$projectSlug/manifest': typeof publicSupportProjectSlugManifestRoute
  '/dashboard/org/$organizationSlug/billing': typeof appDashboardOrgOrganizationSlugBillingRoute
  '/dashboard/org/$organizationSlug/integrations': typeof appDashboardOrgOrganizationSlugIntegrationsRoute
  '/dashboard/org/$organizationSlug/settings': typeof appDashboardOrgOrganizationSlugSettingsRoute
  '/dashboard/org/$organizationSlug/teams': typeof appDashboardOrgOrganizationSlugTeamsRoute
  '/dashboard/org/$organizationSlug/usage': typeof appDashboardOrgOrganizationSlugUsageRoute
  '/dashboard/project/$projectSlug/agents': typeof appDashboardProjectProjectSlugAgentsRoute
  '/dashboard/project/$projectSlug/chat-support': typeof appDashboardProjectProjectSlugChatSupportRoute
  '/dashboard/project/$projectSlug/customers': typeof appDashboardProjectProjectSlugCustomersRoute
  '/dashboard/project/$projectSlug/settings': typeof appDashboardProjectProjectSlugSettingsRoute
  '/dashboard/project/$projectSlug/tickets': typeof appDashboardProjectProjectSlugTicketsRoute
  '/dashboard/org/$organizationSlug/': typeof appDashboardOrgOrganizationSlugIndexRoute
  '/dashboard/project/$projectSlug/': typeof appDashboardProjectProjectSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/reset-password': typeof ResetPasswordRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/signin': typeof authSigninRoute
  '/signup': typeof authSignupRoute
  '/chat': typeof publicChatRoute
  '/api/translate': typeof ApiTranslateRoute
  '/dashboard/organizations': typeof appDashboardOrganizationsRoute
  '/dashboard/triage': typeof appDashboardTriageRoute
  '/api/attachments/$id': typeof ApiAttachmentsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/notification/sse': typeof ApiNotificationSseRoute
  '/api/attachments': typeof ApiAttachmentsIndexRoute
  '/support/$projectSlug/chat-widget': typeof publicSupportProjectSlugChatWidgetRoute
  '/support/$projectSlug/manifest': typeof publicSupportProjectSlugManifestRoute
  '/dashboard/org/$organizationSlug/billing': typeof appDashboardOrgOrganizationSlugBillingRoute
  '/dashboard/org/$organizationSlug/integrations': typeof appDashboardOrgOrganizationSlugIntegrationsRoute
  '/dashboard/org/$organizationSlug/settings': typeof appDashboardOrgOrganizationSlugSettingsRoute
  '/dashboard/org/$organizationSlug/teams': typeof appDashboardOrgOrganizationSlugTeamsRoute
  '/dashboard/org/$organizationSlug/usage': typeof appDashboardOrgOrganizationSlugUsageRoute
  '/dashboard/project/$projectSlug/agents': typeof appDashboardProjectProjectSlugAgentsRoute
  '/dashboard/project/$projectSlug/chat-support': typeof appDashboardProjectProjectSlugChatSupportRoute
  '/dashboard/project/$projectSlug/customers': typeof appDashboardProjectProjectSlugCustomersRoute
  '/dashboard/project/$projectSlug/settings': typeof appDashboardProjectProjectSlugSettingsRoute
  '/dashboard/project/$projectSlug/tickets': typeof appDashboardProjectProjectSlugTicketsRoute
  '/dashboard/org/$organizationSlug': typeof appDashboardOrgOrganizationSlugIndexRoute
  '/dashboard/project/$projectSlug': typeof appDashboardProjectProjectSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(app)': typeof appRouteRouteWithChildren
  '/(auth)': typeof authRouteRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/signin': typeof authSigninRoute
  '/(auth)/signup': typeof authSignupRoute
  '/(public)/chat': typeof publicChatRoute
  '/api/translate': typeof ApiTranslateRoute
  '/(app)/dashboard/organizations': typeof appDashboardOrganizationsRoute
  '/(app)/dashboard/triage': typeof appDashboardTriageRoute
  '/api/attachments/$id': typeof ApiAttachmentsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/notification/sse': typeof ApiNotificationSseRoute
  '/api/attachments/': typeof ApiAttachmentsIndexRoute
  '/(app)/dashboard/org/$organizationSlug': typeof appDashboardOrgOrganizationSlugRouteRouteWithChildren
  '/(app)/dashboard/project/$projectSlug': typeof appDashboardProjectProjectSlugRouteRouteWithChildren
  '/(public)/support/$projectSlug/chat-widget': typeof publicSupportProjectSlugChatWidgetRoute
  '/(public)/support/$projectSlug/manifest': typeof publicSupportProjectSlugManifestRoute
  '/(app)/dashboard/org/$organizationSlug/billing': typeof appDashboardOrgOrganizationSlugBillingRoute
  '/(app)/dashboard/org/$organizationSlug/integrations': typeof appDashboardOrgOrganizationSlugIntegrationsRoute
  '/(app)/dashboard/org/$organizationSlug/settings': typeof appDashboardOrgOrganizationSlugSettingsRoute
  '/(app)/dashboard/org/$organizationSlug/teams': typeof appDashboardOrgOrganizationSlugTeamsRoute
  '/(app)/dashboard/org/$organizationSlug/usage': typeof appDashboardOrgOrganizationSlugUsageRoute
  '/(app)/dashboard/project/$projectSlug/agents': typeof appDashboardProjectProjectSlugAgentsRoute
  '/(app)/dashboard/project/$projectSlug/chat-support': typeof appDashboardProjectProjectSlugChatSupportRoute
  '/(app)/dashboard/project/$projectSlug/customers': typeof appDashboardProjectProjectSlugCustomersRoute
  '/(app)/dashboard/project/$projectSlug/settings': typeof appDashboardProjectProjectSlugSettingsRoute
  '/(app)/dashboard/project/$projectSlug/tickets': typeof appDashboardProjectProjectSlugTicketsRoute
  '/(app)/dashboard/org/$organizationSlug/': typeof appDashboardOrgOrganizationSlugIndexRoute
  '/(app)/dashboard/project/$projectSlug/': typeof appDashboardProjectProjectSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/reset-password'
    | '/forgot-password'
    | '/signin'
    | '/signup'
    | '/chat'
    | '/api/translate'
    | '/dashboard/organizations'
    | '/dashboard/triage'
    | '/api/attachments/$id'
    | '/api/auth/$'
    | '/api/notification/sse'
    | '/api/attachments/'
    | '/dashboard/org/$organizationSlug'
    | '/dashboard/project/$projectSlug'
    | '/support/$projectSlug/chat-widget'
    | '/support/$projectSlug/manifest'
    | '/dashboard/org/$organizationSlug/billing'
    | '/dashboard/org/$organizationSlug/integrations'
    | '/dashboard/org/$organizationSlug/settings'
    | '/dashboard/org/$organizationSlug/teams'
    | '/dashboard/org/$organizationSlug/usage'
    | '/dashboard/project/$projectSlug/agents'
    | '/dashboard/project/$projectSlug/chat-support'
    | '/dashboard/project/$projectSlug/customers'
    | '/dashboard/project/$projectSlug/settings'
    | '/dashboard/project/$projectSlug/tickets'
    | '/dashboard/org/$organizationSlug/'
    | '/dashboard/project/$projectSlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/reset-password'
    | '/forgot-password'
    | '/signin'
    | '/signup'
    | '/chat'
    | '/api/translate'
    | '/dashboard/organizations'
    | '/dashboard/triage'
    | '/api/attachments/$id'
    | '/api/auth/$'
    | '/api/notification/sse'
    | '/api/attachments'
    | '/support/$projectSlug/chat-widget'
    | '/support/$projectSlug/manifest'
    | '/dashboard/org/$organizationSlug/billing'
    | '/dashboard/org/$organizationSlug/integrations'
    | '/dashboard/org/$organizationSlug/settings'
    | '/dashboard/org/$organizationSlug/teams'
    | '/dashboard/org/$organizationSlug/usage'
    | '/dashboard/project/$projectSlug/agents'
    | '/dashboard/project/$projectSlug/chat-support'
    | '/dashboard/project/$projectSlug/customers'
    | '/dashboard/project/$projectSlug/settings'
    | '/dashboard/project/$projectSlug/tickets'
    | '/dashboard/org/$organizationSlug'
    | '/dashboard/project/$projectSlug'
  id:
    | '__root__'
    | '/'
    | '/(app)'
    | '/(auth)'
    | '/reset-password'
    | '/(auth)/forgot-password'
    | '/(auth)/signin'
    | '/(auth)/signup'
    | '/(public)/chat'
    | '/api/translate'
    | '/(app)/dashboard/organizations'
    | '/(app)/dashboard/triage'
    | '/api/attachments/$id'
    | '/api/auth/$'
    | '/api/notification/sse'
    | '/api/attachments/'
    | '/(app)/dashboard/org/$organizationSlug'
    | '/(app)/dashboard/project/$projectSlug'
    | '/(public)/support/$projectSlug/chat-widget'
    | '/(public)/support/$projectSlug/manifest'
    | '/(app)/dashboard/org/$organizationSlug/billing'
    | '/(app)/dashboard/org/$organizationSlug/integrations'
    | '/(app)/dashboard/org/$organizationSlug/settings'
    | '/(app)/dashboard/org/$organizationSlug/teams'
    | '/(app)/dashboard/org/$organizationSlug/usage'
    | '/(app)/dashboard/project/$projectSlug/agents'
    | '/(app)/dashboard/project/$projectSlug/chat-support'
    | '/(app)/dashboard/project/$projectSlug/customers'
    | '/(app)/dashboard/project/$projectSlug/settings'
    | '/(app)/dashboard/project/$projectSlug/tickets'
    | '/(app)/dashboard/org/$organizationSlug/'
    | '/(app)/dashboard/project/$projectSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  appRouteRoute: typeof appRouteRouteWithChildren
  authRouteRoute: typeof authRouteRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  publicChatRoute: typeof publicChatRoute
  ApiTranslateRoute: typeof ApiTranslateRoute
  ApiAttachmentsIdRoute: typeof ApiAttachmentsIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiNotificationSseRoute: typeof ApiNotificationSseRoute
  ApiAttachmentsIndexRoute: typeof ApiAttachmentsIndexRoute
  publicSupportProjectSlugChatWidgetRoute: typeof publicSupportProjectSlugChatWidgetRoute
  publicSupportProjectSlugManifestRoute: typeof publicSupportProjectSlugManifestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)': {
      id: '/(app)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/translate': {
      id: '/api/translate'
      path: '/api/translate'
      fullPath: '/api/translate'
      preLoaderRoute: typeof ApiTranslateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/chat': {
      id: '/(public)/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof publicChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/signup': {
      id: '/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/signin': {
      id: '/(auth)/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof authSigninRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/api/attachments/': {
      id: '/api/attachments/'
      path: '/api/attachments'
      fullPath: '/api/attachments/'
      preLoaderRoute: typeof ApiAttachmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notification/sse': {
      id: '/api/notification/sse'
      path: '/api/notification/sse'
      fullPath: '/api/notification/sse'
      preLoaderRoute: typeof ApiNotificationSseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/attachments/$id': {
      id: '/api/attachments/$id'
      path: '/api/attachments/$id'
      fullPath: '/api/attachments/$id'
      preLoaderRoute: typeof ApiAttachmentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/dashboard/triage': {
      id: '/(app)/dashboard/triage'
      path: '/dashboard/triage'
      fullPath: '/dashboard/triage'
      preLoaderRoute: typeof appDashboardTriageRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/dashboard/organizations': {
      id: '/(app)/dashboard/organizations'
      path: '/dashboard/organizations'
      fullPath: '/dashboard/organizations'
      preLoaderRoute: typeof appDashboardOrganizationsRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(public)/support/$projectSlug/manifest': {
      id: '/(public)/support/$projectSlug/manifest'
      path: '/support/$projectSlug/manifest'
      fullPath: '/support/$projectSlug/manifest'
      preLoaderRoute: typeof publicSupportProjectSlugManifestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/support/$projectSlug/chat-widget': {
      id: '/(public)/support/$projectSlug/chat-widget'
      path: '/support/$projectSlug/chat-widget'
      fullPath: '/support/$projectSlug/chat-widget'
      preLoaderRoute: typeof publicSupportProjectSlugChatWidgetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/dashboard/project/$projectSlug': {
      id: '/(app)/dashboard/project/$projectSlug'
      path: '/dashboard/project/$projectSlug'
      fullPath: '/dashboard/project/$projectSlug'
      preLoaderRoute: typeof appDashboardProjectProjectSlugRouteRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/dashboard/org/$organizationSlug': {
      id: '/(app)/dashboard/org/$organizationSlug'
      path: '/dashboard/org/$organizationSlug'
      fullPath: '/dashboard/org/$organizationSlug'
      preLoaderRoute: typeof appDashboardOrgOrganizationSlugRouteRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/dashboard/project/$projectSlug/': {
      id: '/(app)/dashboard/project/$projectSlug/'
      path: '/'
      fullPath: '/dashboard/project/$projectSlug/'
      preLoaderRoute: typeof appDashboardProjectProjectSlugIndexRouteImport
      parentRoute: typeof appDashboardProjectProjectSlugRouteRoute
    }
    '/(app)/dashboard/org/$organizationSlug/': {
      id: '/(app)/dashboard/org/$organizationSlug/'
      path: '/'
      fullPath: '/dashboard/org/$organizationSlug/'
      preLoaderRoute: typeof appDashboardOrgOrganizationSlugIndexRouteImport
      parentRoute: typeof appDashboardOrgOrganizationSlugRouteRoute
    }
    '/(app)/dashboard/project/$projectSlug/tickets': {
      id: '/(app)/dashboard/project/$projectSlug/tickets'
      path: '/tickets'
      fullPath: '/dashboard/project/$projectSlug/tickets'
      preLoaderRoute: typeof appDashboardProjectProjectSlugTicketsRouteImport
      parentRoute: typeof appDashboardProjectProjectSlugRouteRoute
    }
    '/(app)/dashboard/project/$projectSlug/settings': {
      id: '/(app)/dashboard/project/$projectSlug/settings'
      path: '/settings'
      fullPath: '/dashboard/project/$projectSlug/settings'
      preLoaderRoute: typeof appDashboardProjectProjectSlugSettingsRouteImport
      parentRoute: typeof appDashboardProjectProjectSlugRouteRoute
    }
    '/(app)/dashboard/project/$projectSlug/customers': {
      id: '/(app)/dashboard/project/$projectSlug/customers'
      path: '/customers'
      fullPath: '/dashboard/project/$projectSlug/customers'
      preLoaderRoute: typeof appDashboardProjectProjectSlugCustomersRouteImport
      parentRoute: typeof appDashboardProjectProjectSlugRouteRoute
    }
    '/(app)/dashboard/project/$projectSlug/chat-support': {
      id: '/(app)/dashboard/project/$projectSlug/chat-support'
      path: '/chat-support'
      fullPath: '/dashboard/project/$projectSlug/chat-support'
      preLoaderRoute: typeof appDashboardProjectProjectSlugChatSupportRouteImport
      parentRoute: typeof appDashboardProjectProjectSlugRouteRoute
    }
    '/(app)/dashboard/project/$projectSlug/agents': {
      id: '/(app)/dashboard/project/$projectSlug/agents'
      path: '/agents'
      fullPath: '/dashboard/project/$projectSlug/agents'
      preLoaderRoute: typeof appDashboardProjectProjectSlugAgentsRouteImport
      parentRoute: typeof appDashboardProjectProjectSlugRouteRoute
    }
    '/(app)/dashboard/org/$organizationSlug/usage': {
      id: '/(app)/dashboard/org/$organizationSlug/usage'
      path: '/usage'
      fullPath: '/dashboard/org/$organizationSlug/usage'
      preLoaderRoute: typeof appDashboardOrgOrganizationSlugUsageRouteImport
      parentRoute: typeof appDashboardOrgOrganizationSlugRouteRoute
    }
    '/(app)/dashboard/org/$organizationSlug/teams': {
      id: '/(app)/dashboard/org/$organizationSlug/teams'
      path: '/teams'
      fullPath: '/dashboard/org/$organizationSlug/teams'
      preLoaderRoute: typeof appDashboardOrgOrganizationSlugTeamsRouteImport
      parentRoute: typeof appDashboardOrgOrganizationSlugRouteRoute
    }
    '/(app)/dashboard/org/$organizationSlug/settings': {
      id: '/(app)/dashboard/org/$organizationSlug/settings'
      path: '/settings'
      fullPath: '/dashboard/org/$organizationSlug/settings'
      preLoaderRoute: typeof appDashboardOrgOrganizationSlugSettingsRouteImport
      parentRoute: typeof appDashboardOrgOrganizationSlugRouteRoute
    }
    '/(app)/dashboard/org/$organizationSlug/integrations': {
      id: '/(app)/dashboard/org/$organizationSlug/integrations'
      path: '/integrations'
      fullPath: '/dashboard/org/$organizationSlug/integrations'
      preLoaderRoute: typeof appDashboardOrgOrganizationSlugIntegrationsRouteImport
      parentRoute: typeof appDashboardOrgOrganizationSlugRouteRoute
    }
    '/(app)/dashboard/org/$organizationSlug/billing': {
      id: '/(app)/dashboard/org/$organizationSlug/billing'
      path: '/billing'
      fullPath: '/dashboard/org/$organizationSlug/billing'
      preLoaderRoute: typeof appDashboardOrgOrganizationSlugBillingRouteImport
      parentRoute: typeof appDashboardOrgOrganizationSlugRouteRoute
    }
  }
}

interface appDashboardOrgOrganizationSlugRouteRouteChildren {
  appDashboardOrgOrganizationSlugBillingRoute: typeof appDashboardOrgOrganizationSlugBillingRoute
  appDashboardOrgOrganizationSlugIntegrationsRoute: typeof appDashboardOrgOrganizationSlugIntegrationsRoute
  appDashboardOrgOrganizationSlugSettingsRoute: typeof appDashboardOrgOrganizationSlugSettingsRoute
  appDashboardOrgOrganizationSlugTeamsRoute: typeof appDashboardOrgOrganizationSlugTeamsRoute
  appDashboardOrgOrganizationSlugUsageRoute: typeof appDashboardOrgOrganizationSlugUsageRoute
  appDashboardOrgOrganizationSlugIndexRoute: typeof appDashboardOrgOrganizationSlugIndexRoute
}

const appDashboardOrgOrganizationSlugRouteRouteChildren: appDashboardOrgOrganizationSlugRouteRouteChildren =
  {
    appDashboardOrgOrganizationSlugBillingRoute:
      appDashboardOrgOrganizationSlugBillingRoute,
    appDashboardOrgOrganizationSlugIntegrationsRoute:
      appDashboardOrgOrganizationSlugIntegrationsRoute,
    appDashboardOrgOrganizationSlugSettingsRoute:
      appDashboardOrgOrganizationSlugSettingsRoute,
    appDashboardOrgOrganizationSlugTeamsRoute:
      appDashboardOrgOrganizationSlugTeamsRoute,
    appDashboardOrgOrganizationSlugUsageRoute:
      appDashboardOrgOrganizationSlugUsageRoute,
    appDashboardOrgOrganizationSlugIndexRoute:
      appDashboardOrgOrganizationSlugIndexRoute,
  }

const appDashboardOrgOrganizationSlugRouteRouteWithChildren =
  appDashboardOrgOrganizationSlugRouteRoute._addFileChildren(
    appDashboardOrgOrganizationSlugRouteRouteChildren,
  )

interface appDashboardProjectProjectSlugRouteRouteChildren {
  appDashboardProjectProjectSlugAgentsRoute: typeof appDashboardProjectProjectSlugAgentsRoute
  appDashboardProjectProjectSlugChatSupportRoute: typeof appDashboardProjectProjectSlugChatSupportRoute
  appDashboardProjectProjectSlugCustomersRoute: typeof appDashboardProjectProjectSlugCustomersRoute
  appDashboardProjectProjectSlugSettingsRoute: typeof appDashboardProjectProjectSlugSettingsRoute
  appDashboardProjectProjectSlugTicketsRoute: typeof appDashboardProjectProjectSlugTicketsRoute
  appDashboardProjectProjectSlugIndexRoute: typeof appDashboardProjectProjectSlugIndexRoute
}

const appDashboardProjectProjectSlugRouteRouteChildren: appDashboardProjectProjectSlugRouteRouteChildren =
  {
    appDashboardProjectProjectSlugAgentsRoute:
      appDashboardProjectProjectSlugAgentsRoute,
    appDashboardProjectProjectSlugChatSupportRoute:
      appDashboardProjectProjectSlugChatSupportRoute,
    appDashboardProjectProjectSlugCustomersRoute:
      appDashboardProjectProjectSlugCustomersRoute,
    appDashboardProjectProjectSlugSettingsRoute:
      appDashboardProjectProjectSlugSettingsRoute,
    appDashboardProjectProjectSlugTicketsRoute:
      appDashboardProjectProjectSlugTicketsRoute,
    appDashboardProjectProjectSlugIndexRoute:
      appDashboardProjectProjectSlugIndexRoute,
  }

const appDashboardProjectProjectSlugRouteRouteWithChildren =
  appDashboardProjectProjectSlugRouteRoute._addFileChildren(
    appDashboardProjectProjectSlugRouteRouteChildren,
  )

interface appRouteRouteChildren {
  appDashboardOrganizationsRoute: typeof appDashboardOrganizationsRoute
  appDashboardTriageRoute: typeof appDashboardTriageRoute
  appDashboardOrgOrganizationSlugRouteRoute: typeof appDashboardOrgOrganizationSlugRouteRouteWithChildren
  appDashboardProjectProjectSlugRouteRoute: typeof appDashboardProjectProjectSlugRouteRouteWithChildren
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appDashboardOrganizationsRoute: appDashboardOrganizationsRoute,
  appDashboardTriageRoute: appDashboardTriageRoute,
  appDashboardOrgOrganizationSlugRouteRoute:
    appDashboardOrgOrganizationSlugRouteRouteWithChildren,
  appDashboardProjectProjectSlugRouteRoute:
    appDashboardProjectProjectSlugRouteRouteWithChildren,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

interface authRouteRouteChildren {
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authSigninRoute: typeof authSigninRoute
  authSignupRoute: typeof authSignupRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authForgotPasswordRoute: authForgotPasswordRoute,
  authSigninRoute: authSigninRoute,
  authSignupRoute: authSignupRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  appRouteRoute: appRouteRouteWithChildren,
  authRouteRoute: authRouteRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  publicChatRoute: publicChatRoute,
  ApiTranslateRoute: ApiTranslateRoute,
  ApiAttachmentsIdRoute: ApiAttachmentsIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiNotificationSseRoute: ApiNotificationSseRoute,
  ApiAttachmentsIndexRoute: ApiAttachmentsIndexRoute,
  publicSupportProjectSlugChatWidgetRoute:
    publicSupportProjectSlugChatWidgetRoute,
  publicSupportProjectSlugManifestRoute: publicSupportProjectSlugManifestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
